# Generated by Django 2.2.4 on 2019-08-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='unique_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='subdomain',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
